website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
DB_NAME = "/home/kentanto65/web-app-game/instance/deathgamecharacters.db"

def init_game():
    game = Flask(__name__)
    game.config["SECRET_KEY"] = "ye atomic's pretty good"
    game.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(game)

    from .views import head
    game.register_blueprint(head, url_prefix='/')

    return game

website/views.py
from flask import Blueprint, flash, render_template, request, jsonify
from .model import Admin, Dead_people, Items, People, Picked_characters, Picked_names, Teams
from . import db
from datetime import datetime
import random
head = Blueprint("head", __name__)

@head.route("/")
def home():
    return render_template("index.html")

@head.route("/cursed_home")
def cursed_home():
    return render_template("cursed/cursed_home.html")

@head.route("/admin")
def view_admin():
    admin = Admin.query.all()
    return render_template("db_template/admin.html", admin=admin)

@head.route("/dead_people")
def view_dead_people():
    dead = Dead_people.query.all()
    return render_template("db_template/dead_people.html", dead=dead)

@head.route("/items")
def view_items():
    items = Items.query.all()
    return render_template("db_template/items.html", items=items)

@head.route("/people")
def view_people():
    people = People.query.all()
    return render_template("db_template/people.html", people=people)

@head.route("/picked_names")
def view_picked_names():
    picked_names = Picked_names.query.all()
    return render_template("db_template/picked_names.html", picked_names=picked_names)

@head.route("/teams")
def view_teams():
    teams = Teams.query.all()
    return render_template("db_template/teams.html", teams=teams)

@head.route("/check_modfiy_person", methods=["POST"])
def check_or_modify():
    person_name = request.form["person_name"]
    modify_person = request.form.get("modify_person")
    modification_type = request.form.get("modification_type")
    additional_info = request.form.get("additional_info")

    person = People.query.filter_by(name=person_name).first()
    if person:
        if modify_person == "yes":
            if modification_type in ["alive", "disabled"]:
                person.status = modification_type
                dead_person = Dead_people.query.filter_by(names=person_name).first()
                if dead_person:
                    db.session.delete(dead_person)
                db.session.commit()
            elif modification_type == "injured":
                    person.status = f"{modification_type} by: {additional_info}"
                    db.session.commit()
            elif modification_type == "Custom":
                    person.status = additional_info
                    db.session.commit()
    
    return jsonify({'message': 'Success'})

@head.route("/kill_person", methods=["POST"])
def kill_Person():
    person_to_kill = request.form["target_person"]
    killer = request.form["killer"]
    person_to_die = People.query.filter_by(name=person_to_kill).first()
    if person_to_die:
        person_to_die.status = f"dead: ({killer})"
        person_to_die.items_use = ""
        dead_person_entry = Dead_people(names=person_to_kill, killer=killer, time_died=datetime.now())
        db.session.add(dead_person_entry)
        db.session.commit()
    return jsonify({'message': 'Success'})

@head.route("/get_person_info", methods=["POST"])
def get_person_info():
    person_name = request.json["person_name"]
    if person_name:
        person = People.query.filter_by(name=person_name).first()
        if person:
            html = f"<p>Name: {person.name}</p>"
            html += f"<p>Status: {person.status}</p>"
            html += f"<p>Items Use: {person.items_use}</p>"
            return jsonify({"html": html})
        else:
            return jsonify({"html": "<p>Person not found</p>"})
        
    

def wagner_fischer(s1, s2):
    len_s1, len_s2 = len(s1), len(s2)
    if len_s1 > len_s2:
        s1, s2 = s2, s1
        len_s1, len_s2 = len_s2, len_s1

    current_row = range(len_s1 + 1)
    for i in range(1, len_s2 + 1):
        previous_row, current_row = current_row, [i] + [0] * len_s1
        for j in range(1, len_s1 + 1):
            add, delete, change = previous_row[j] + 1, current_row[j-1] + 1, previous_row[j-1]
            if s1[j-1] != s2[i-1]:
                change += 1
            current_row[j] = min(add, delete, change)

    return current_row[len_s1]


@head.route("/spell_check", methods=["POST"])
def spell_check():
    word = request.form.get("word")
    dictionary = People.query.with_entities(People.name).all()
    suggestions = []

    for row in dictionary:
        correct_word = row[0]
        distance = wagner_fischer(word, correct_word)
        suggestions.append((correct_word, distance))

    suggestions.sort(key=lambda x: x[1])
    return jsonify({"suggestions": suggestions[:1]})

@head.route("/reset_game", methods=["post"] )
def reset_game():    
    the_one_the_only_password = "213"
    password = request.form.get("password")
    item_availability = {
    "Tail wag of doom": 2,
    "Yawn of doom": 2,
    "Mystery game": 1,
    "God's mercy": 1,
    "D'baguette": 1,
    "Eh'Syrup": 1,
    "Raphael": 1,
    "Atomic's curse": 1,
    "Button of doom": 2,
    "Senseless cloak": 1,
    "Air strike of doom": 1,
    "talk no jutsu": 1,
    "Goal-post of doom": 1,
    "Open net": 1,
    "120 Ping": 1
    }

    if password == the_one_the_only_password:
        new_seed = random.randint(1, 1000000)
        admin_record = Admin.query.first()
        admin_record.Seed = new_seed
        Dead_people.query.delete()
        items = Items.query.all()
        for item in items:
            if item.item_name in item_availability:
                item.availability = item_availability[item.item_name]
        people = People.query.all()
        for person in people:
            person.status = "alive"
            person.items_use = ""        
        Picked_characters.query.delete()
        Picked_names.query.delete()
        Teams.query.delete()        
        db.session.commit()
    
    return render_template("index.html")

website/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %} - Deathgame</title>
  <link rel="stylesheet" href="{{ url_for("static", filename="style.css") }}">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <span class="navbar-toggler-icon"></span>
  <div class="collapse navbar-collapse" id="navbar">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item"><a class="nav-link btn" href="/">Home</a></li> 
        <li class="nav-item"><a class="nav-link btn" href="/cursed_home">Cursed Home</a></li>
        <li class="nav-item"><a class="nav-link btn" href="/">Coming Soon...</a></li>
    </ul>
  </div>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>
</html>

website/templates/cursed/cursed_home.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %} - Deathgame</title>
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">-->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <script src="//gravityscript.github.io/grav.js"></script>
    

<!--
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> 
-->

<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>
<body>   
  <div id="RimShadow-right"></div> 
  <div id="RimShadow-left"></div>
  <div id="RimShadow-top"></div>
  <div id="RimShadow-bottom"></div>
    <div class="container">        
        <div class="btn-container-cursed">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="gone">
                <span class="navbar-toggler-icon"></span>
                <div class="collapse navbar-collapse" id="navbar">
                    <ul class="navbar-nav mr-auto btn-container-cursed">
                        <li class="nav-item"><a class="nav-link btn" href="/">Home</a></li> 
                        <li class="nav-item"><a class="nav-link btn" href="/cursed_home">Cursed Home</a></li>
                        <li class="nav-item"><a class="nav-link btn" href="/">Coming Soon...</a></li>
                    </ul>
                </div>
            </nav>
            <a class='ohGodGoBack' href="/">OH GOD GO BACK!!!</a>
            <a class="btn" id="check-modify-btn">Check/Modify A Person</a>
            <a class="btn" onclick="kill_person()">Kill A Person</a>
            <a class="btn" onclick="add_or_remove()">Add/Remove</a>
            <a class="btn" onclick="create_modify_team()">Create Or Modify A Team</a>
            <a class="btn" href="{{ url_for('head.view_dead_people') }}">Dead Status</a>
            <a class="btn" href="{{ url_for('head.view_people') }}">Status</a>
            <a class="btn" onclick="reset_program()">Reset Game</a>
            <a class="btn" onclick="display_picked_names()">Pick Names</a>
            <a class="btn" onclick="kill_count()">Kill Count</a>
            <a class="btn" href="{{ url_for('head.view_items') }}">Items</a>
            <a class="btn" onclick="on_opening_admin()">Mass Kill</a>
            <a class="btn" href="{{ url_for('head.view_picked_names') }}">Appearances</a>
            <a class="btn" href="{{ url_for('head.view_teams') }}">Teams</a>
        </div>
    </div>
    <div class="under_bar"></div>
    <div id="check_and_modify">
      <div class="form-container">
          <h1>Check or Modify a Person</h1>
          <form id="person-form" action="/check_modfiy_person" method="post">
              <label for="person_name">Person's Name:</label>
              <input required type="text" id="person_name" name="person_name">
              
              <label for="modify_person">Modify this person?</label>
              <select id="modify_person" name="modify_person">
                  <option value="yes">Yes</option>
                  <option value="no">No</option>
              </select>
              <label for="modification_type">Modification Type:</label>
              <select id="modification_type" name="modification_type">
                  <option value="alive">Alive</option>
                  <option value="injured">Injured</option>                    
                  <option value="disabled">Disabled</option>
              </select>
              <div id="injuredByInput" style="display: none;">
                  <label for="additional_info">Injured by?</label>
                  <input type="text" id="additional_info" name="additional_info">
              </div>               
              <button type="submit">Submit</button>
          </form>
          <div id="person-info"></div>
          <div> did you mean?: <div id="spell-suggestions"></div></div>
      </div>
  </div>
</body>

website/templates/db_template/admin.html
{% extends 'base.html' %}
{% block title %}Admin{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
<body>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <h1>Admin Information</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Status</th>
                <th>Seed</th>
            </tr>
        </thead>
        <tbody>
            {% for admin in admin %}
            <tr>
                <td>{{ admin.id }}</td>
                <td>{{ admin.Admin }}</td>
                <td>{{ admin.Status }}</td>
                <td>{{ admin.Seed }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
{% endblock %}

website/templates/db_template/dead_people.html
{% extends 'base.html' %}
{% block title %}Dead People{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
<body>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <h1>Dead People</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Killed By</th>
                <th>Time Died</th>
            </tr>
        </thead>
        <tbody>
            {% for dead in dead %}
            <tr>
                <td>{{ dead.id }}</td>
                <td>{{ dead.names }}</td>
                <td>{{ dead.killer }}</td>
                <td>{{ dead.time_died }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
{% endblock %}

website/templates/db_template/items.html
{% extends 'base.html' %}
{% block title %}Items{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
<body>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <h1>Item Information</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Item Name</th>
                <th>Description</th>
                <th>Availability</th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.item_name }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.availability }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
{% endblock %}

website/templates/db_template/people.html
{% extends 'base.html' %}
{% block title %}People{% endblock %}
{% block header %}
<ul class="filter-options">
    <li>
        <input type="checkbox" id="filter-alive" checked>
        <label for="filter-alive">Alive</label>
    </li>
    <li>
        <input type="checkbox" id="filter-dead" checked>
        <label for="filter-dead">Dead</label>
    </li>
</ul>
{% endblock %}
{% block content %}
<body>    
    <script src="static/statusFiltering.js"></script>    
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <div class="people-grid">
        {% for person in people %}
        <div class="person" data-status="{{ person.status }}">
            <div class="person-image">
                <img src="{{ url_for('static', filename='images/' + person.name + '.jpg') }}" alt="{{ person.name }}">
            </div>
                <p><strong>ID:</strong> {{ person.id }}</p>
                <p><strong>Name:</strong> {{ person.name }}</p>
                <p><strong>Status:</strong> {{ person.status }}</p>
                <p><strong>Items in Use:</strong> {{ person.items_use }}</p>
        </div>
        {% endfor %}
    </div>
</body>
{% endblock %}

website/templates/db_template/picked_names.html
{% extends 'base.html' %}
{% block title %}Picked Names{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
<body>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <h1>Picked Names</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Count</th>
                <th>Time Picked</th>
            </tr>
        </thead>
        <tbody>
            {% for picked_name in picked_names %}
            <tr>
                <td>{{ picked_name.id }}</td>
                <td>{{ picked_name.name }}</td>
                <td>{{ picked_name.count }}</td>
                <td>{{ picked_name.time_picked }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
{% endblock %}

website/templates/db_template/teams.html
{% extends 'base.html' %}
{% block title %}Teams{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
<body>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <h1>Teams</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Team Name</th>
                <th>Member Name</th>
            </tr>
        </thead>
        <tbody>
            {% for team in teams %}
            <tr>
                <td>{{ team.id }}</td>
                <td>{{ team.team_name }}</td>
                <td>{{ team.member_name }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
{% endblock %}

website/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block header %}
{% endblock %}
{% block content %}

<body>
    <script src="static/slide_In_functions.js"></script>
    <script src="static/autocorrect.js"></script>
    <div id="main-page-content">
    <div id="RimShadow-right"></div>
    <div id="RimShadow-left"></div>
    <div id="RimShadow-top"></div>
    <div id="RimShadow-bottom"></div>
    <div id="overlapshadow-top"></div>
    <div id="overlapshadow-bottom"></div>
    <div id="overlapshadow-left"></div>
    <div id="overlapshadow-right"></div>
    <div class="container">
        <div class="btn-container">
            <a class="btn" id="check-modify-btn">Check/Modify A Person</a>
            <a class="btn" id="kill-person-btn">Kill A Person</a>
            <a class="btn" onclick="add_or_remove()">Add/Remove</a>
            <a class="btn" onclick="create_modify_team()">Create Or Modify A Team</a>
            <a class="btn" href="{{ url_for("head.view_dead_people") }}">Dead Status</a>
            <a class="btn" href="{{ url_for("head.view_people") }}">Status</a>
            <a class="btn" id="reset-game-btn">Reset Game</a>
            <a class="btn" onclick="display_picked_names()">Pick Names</a>
            <a class="btn" onclick="kill_count()">Kill Count</a>
            <a class="btn" href="{{ url_for("head.view_items") }}">Items</a>
            <a class="btn" onclick="on_opening_admin()">Mass Kill</a>
            <a class="btn" href="{{ url_for("head.view_picked_names") }}">Appearances</a>
            <a class="btn" href="{{ url_for("head.view_teams") }}">Teams</a>
        </div>
    </div>
    <div class="under_bar"></div>
    </div>
    <div id="check_and_modify">
        <div class="form-container">
            <h1>Check or Modify a Person</h1>
            <form id="person-form" action="/check_modfiy_person" method="post">
                <label for="person_name">Person's Name:</label>
                <input required type="text" id="person_name" name="person_name">

                <label for="modify_person">Modify this person?</label>
                <select id="modify_person" name="modify_person">
                    <option value="yes">Yes</option>
                    <option value="no">No</option>
                </select>
                <label for="modification_type">Modification Type:</label>
                <select id="modification_type" name="modification_type">
                    <option value="alive">Alive</option>
                    <option value="injured">Injured</option>
                    <option value="disabled">Disabled</option>
                    <option value="Custom">Other</option>
                </select>
                <div id="Extra_Info" style="display: none;">
                    <label for="additional_info">label text</label>
                    <input type="text" id="additional_info" name="additional_info">
                </div>
                <button type="submit">Submit</button>
            </form>
            <div id="person-info"></div>
            <div> did you mean?: <div id="check-spell-suggestions"></div></div>
        </div>
    </div>
    <div id="kill_Person_container" class="hidden">
        <div class="form-container" style="width: 400px;">
            <h1 style="font-size: 36px;">Kill Person</h1>
            <form id="kill-person-form" action="/kill_person" method="post">
                <label for="target_person" style="font-size: 27px;">Target Person:</label>
                <input required type="text" id="target_person" name="target_person" style="width: 100%; padding: 8px; font-size: 24px;">

                <label for="killer" style="font-size: 27px;">Killer:</label>
                <input required type="text" id="killer" name="killer" style="width: 100%; padding: 8px; font-size: 24px;">

                <button class="main_gradient" type="submit" style="width: 100%; padding: 10px; font-size: 27px;">Kill</button>

            </form>

            <div id="person-info"></div>
                <div> did you mean?: <div id="kill-spell-suggestions"></div></div>
        </div>
    </div>
    <div id="password-form-container" class="hidden">
        <div class="form-container">
            <h1 style="font-size: 25px;">I'll be needing a password for this one m8</h1>
            <form id="password-submit-form" action="/reset_game" method="post">
                <label for="password" style="font-size: 20px;">Password:</label>
                <input required id="password" name="password" style="width: 95%; padding: 8px; font-size: 18px;">
                <button class="main_gradient" type="submit" style="width: 100%; padding: 10px; font-size: 18px;">Submit</button>
            </form>
        </div>
    </div>
</body>
{% endblock %}